# This file is for local development overrides.
# For example, you can use it to mount local volumes for development.

services:
  be:
    # Ensure dependencies are installed before running the dev server
    command: ["sh", "-c", "npm install && npm run start:dev"]
    ports:
      - "9229:9229" # Node.js inspect port
      - "3000:3000" # map backend port to host for local dev

  fe: {}
