version: '3'

services:  
  # Name our service will be known by
  mongoDb:
    container_name: "exam-mongodb-service"
    # version of mongo we'll use
    image: mongo:4.2

    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword

    # local port mapping to container port.  Remember, this
    # doesn't have to be 27017, you could make this availble
    # on port 3000 on our local machine via 3000:27017
    # if we really wanted to.
    ports:
      - 27017:27017

    # using a named volume
    volumes:
      - mongodb_data_container:/data/db

    # OPTIONAL: This enforces the need for authentication
    command: mongod --auth

volumes:  
  mongodb_data_container:
